name: C/C++ CI

on:
  workflow_dispatch


jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: configure whats this even for
      # run: ./configure
    - name: Compiling...
      run: |
        cd EasyTracer # got cd into the project folder
        g++ -Iexternal/src/include -Lexternal/src/lib -o dist/EasyTracer_UBUNTU src/main.c src/tracer.c src/primitives.c src/types.c -l:libSDL2main.a -l:libSDL2.dll.a 

    - name: Pushing results...
      run: |
        git config --global user.name 'RuiFilipeCampos'
        git config --global user.email 'RuiFilipeCampos@users.noreply.github.com'
        git add .
        git commit -am "Automated build (ubuntu)"
        git push
    
    # - name: make check
    #  run: make check
    # - name: make distcheck
    #  run: make distcheck
