name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: configure whats this even for
      # run: ./configure
    - name: Compiling...
      run: |
        cd EasyTracer # got cd into the project folder
        g++ -Isrc/include -Lsrc/lib -o EasyTracer_UBUNTU main.c tracer.c primitives.c types.c -l:libSDL2main.a -l:libSDL2.dll.a
    - name: Pushing results...
      run: |
        git config --global user.name 'RuiFilipeCampos'
        git config --global user.email 'RuiFilipeCampos@users.noreply.github.com'
        git add EasyTracer_UBUNTU
        git commit -am "Automated build (ubuntu)"
        git push
    
    # - name: make check
    #  run: make check
    # - name: make distcheck
    #  run: make distcheck
