name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: configure whats this even for
      # run: ./configure
    - name: make
      run: |
        cd EasyTracer # got cd into the project folder
        	g++ -Isrc/include -Lsrc/lib -o main main.c tracer.c primitives.c types.c -l:libSDL2main.a -l:libSDL2.dll.a
        
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
